# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/tti
    REF boost-1.84.0.beta1
    SHA512 a4d7682b91531b01942615ae9dc73e6e5be965eeaebc35ef53decf7320c7c2d17269c8e2f0fe6bf5e7d44ddd39a7692163b567db4022fef7c558710cee8fc1ae
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
