# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/phoenix
    REF boost-1.84.0.beta1
    SHA512 a6294b3ace2d93cd6f379d209a176026d6ee3d9269af8c9c295c68fd44f7532d15ae6e33a0b54233d9775f8fe2833457c532a7a931a7d0880200e3bcd943bf86
    HEAD_REF master
    PATCHES fix-duplicate-symbols.patch
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
