# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/phoenix
    REF 8913607a3788cb82d48ed461ea59c919b7bad3df
    SHA512 85291e923d7b79e9b7e4ebbc101fa7e80d9f4614a268dec0c3f12697e7c0796698d7e20575fbdb585905f65a666c70c2466b5568c8ec985c56797da035fdc570
    HEAD_REF develop
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
