# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/type_traits
    REF 1ebd31e60eab91bd8bdc586d8df00586ecfb53e4
    SHA512 d84e0d56f0d134f31defa1f5e8b86509cf3978e457de90ae70612e91d314919de0016f86e58e39299ed2381275377ad4ee17cce10797b8964f6236f01010c604
    HEAD_REF develop
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
