# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/type_traits
    REF boost-1.84.0.beta1
    SHA512 c433b5c3ced3658dc5066edc027ec1886872f7cacad89a6fea1c2a67e47d0759210d2e6e356a38dc895ef2d699eca77f65288ea4f45119ab06ee55a28f88989f
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
