# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/align
    REF boost-1.84.0.beta1
    SHA512 8e775f09a445baccf5f6a12cf6661e816d1c81e9d6656580498825aceb7753f1c72682e0420e0c6227f5b244a970a03cb3dcd09bb9f288c5f0ea598ccc3d267a
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
