# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/contract
    REF eca93d24b5d3bb909ed64c12b5feb5296c5cc070
    SHA512 f117bb65e8b962fdb8958af47eeabd6b98c39b41d27a810284526d49b114caa538910de1ab293623ea6a2ecf433cef53278316ab014b26d731387952422a8b31
    HEAD_REF develop
)

include(${CURRENT_HOST_INSTALLED_DIR}/share/boost-build/boost-modular-build.cmake)
boost_modular_build(SOURCE_PATH ${SOURCE_PATH})
include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
