# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/tuple
    REF boost-1.84.0.beta1
    SHA512 fbf04c2f268519d5b509fc8ebafa3188c8ba3b6f3c3dd14d0a9c54a8ab2b65d3bb974c853976088bdc9fec82f898bedaa3e46c931c9f6708534cf55a3e4c12e4
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
