# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/tuple
    REF 453e061434be75ddd9e4bc578114a4ad9ce0f706
    SHA512 344065981b5c266a8afebd79c72397736486d88f6309948bb76e13f674ba96450476d422f344a5642208a8df4787723cd40d2551cf8226c1951f57c6dd8b228a
    HEAD_REF develop
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
