# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/odeint
    REF 2bbc186b43d7267e622c4e1ad9527e4a8ecc8c42
    SHA512 068e45ff51b3ea5488196ebf2272237f702fc23eb36cea35cc43d482ad022f63640bacd169ab6137aa6180e7986866977a26453edd5d95681d77224b55b639d6
    HEAD_REF develop
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
