# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/odeint
    REF boost-1.84.0.beta1
    SHA512 b121e234024fe70c3e34d60850b7d7f873ab04dfb807d37357a11c01793dcb5c68b61a9d41b2b355ac8ce30c7f1cc128ed336765a17e7bb87fbce10adc2568c9
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
