# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/iostreams
    REF 7c21f2d8663b62bb3257bfcdd326915bc928c48b
    SHA512 8f5433a917023a7d663783b00c5566237c41a7ea3be4c6d0f68fb13dddc4c9f6ad5cee26d1f7b09734bccd6c33308c14aad7988ebf2a89acf9eb2f4f2baa401b
    HEAD_REF develop
)

include(${CURRENT_HOST_INSTALLED_DIR}/share/boost-build/boost-modular-build.cmake)
boost_modular_build(SOURCE_PATH ${SOURCE_PATH})
include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
