# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/sync
    REF e3b397214fc87e0f9802c6140e7af4ce68bdbb80
    SHA512 4227905a9175599e73f0ecae18772644da0c2b92dc12e1fe72f95593b45a91393530e189beb316af1614b1498ca87128d82b77f3a3e18e79c7b5916facb67073
    HEAD_REF develop
)

include(${CURRENT_HOST_INSTALLED_DIR}/share/boost-build/boost-modular-build.cmake)
boost_modular_build(SOURCE_PATH ${SOURCE_PATH})
include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
