# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/compatibility
    REF boost-1.84.0.beta1
    SHA512 bf66334dc4b280757dac47f414b1ae31eca6a44225bcaedd13428d77bb758248164da1aea624c302f80350189ab01568459ecc60f65f53a6658fd5398eb17dcf
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
