# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/functional
    REF boost-1.84.0.beta1
    SHA512 86b96814856e9b5140a2dcd175e52363d665ae4eb3703b9217a2dcc79494f6c28c26a13655a90ffaf3af0c4b06c160d5ff2fc9997d52652a303afe6dab565dfa
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
