# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/predef
    REF e508ed842c153b5dd4858e2cdafd58d2ede418d4
    SHA512 7452f47cc24be17f3acfdd47877eb4814f499c0ad82b634b5ecfff20892ae1fb5360872daa7b0846ef0fb9b37431341eb1a36f32173f699c017a7315903ea0ef
    HEAD_REF develop
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})

file(COPY ${SOURCE_PATH}/tools/check DESTINATION ${CURRENT_PACKAGES_DIR}/share/boost-predef)
