# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/exception
    REF fe23c01a93757117916e6b8dd393ab2ecabf16bc
    SHA512 2b2a70c763ca3067a620f811280a677de7d2a7b482ff9f39507fa5a61f4b7fef9aa691a940dfe70d6e8122fba557c7bf1edd2443eb84be76b8f760b524b261e0
    HEAD_REF develop
)

include(${CURRENT_HOST_INSTALLED_DIR}/share/boost-build/boost-modular-build.cmake)
boost_modular_build(SOURCE_PATH ${SOURCE_PATH})
include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
