# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/throw_exception
    REF 23dd41e920ecd91237500ac6428f7d392a7a875c
    SHA512 026ad35a275108415ed5d907b926480c0c9d401aa28b7542fd1113a3233788f678d39069aa4bc261f10fb8c5dd4e4d8a67b263c48967691b082afbafa817a31c
    HEAD_REF develop
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
