# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/type_index
    REF 29ab3258a73215c67598383696c927887fc0cfeb
    SHA512 b0b0c2897ceab5f264cb684e3451de9ae8ebca232e5d42080f7332a8a6fea9e16812f974a4e8064e0bdb0f0aa8a2f1d2d7c1597c8547758a6f9c6933ebb7f387
    HEAD_REF develop
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
