# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/type_index
    REF boost-1.84.0.beta1
    SHA512 1f7582c18d42f665a729c6c4369bd3c37e4f745720a8e67b5a9e93d16b9cc7d667b9f62b6da793d404a182a9b38d38df6d5d38ec9b7f9ff0b3904fdf3c621673
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
