# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/smart_ptr
    REF boost-1.84.0.beta1
    SHA512 ac8efad9b6d1cce2d5cea7cdecbc3cc6fc95124490a5cc43498f25ccf88f6748747bb46568eaba1b0f28df3346276cf9f01ee5bef6083aa4737184dc2858376d
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
