# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/smart_ptr
    REF 13be03abf880cdb616d0597c38880f53f1b415b8
    SHA512 ca4706072881bd9b72f1b68ced2b47dd80b847dc987dbea667aaa680fc800509354fb00095d5b04f16ec9bb697ecbfcc7270eef11722e4dfaeacf3e8b682e892
    HEAD_REF develop
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
