# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/stacktrace
    REF dc5cd9d1f393299e5210d0acb92e97bf455e5e9a
    SHA512 d7864d86241eb6b4a2558544f99549cd6be484abf1860c018e903c88799cd58db2ed8fcec069e11ec3619a95a1f44126ab9d1e60646d0e37f1f2390d068108ea
    HEAD_REF develop
)

include(${CURRENT_HOST_INSTALLED_DIR}/share/boost-build/boost-modular-build.cmake)
boost_modular_build(SOURCE_PATH ${SOURCE_PATH})
include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
