# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/interval
    REF 2eda7413ac16dd4158005446438daf8a7e435dd9
    SHA512 4da598bf6a81d5629d743e3f79a95ee7ab16f4653953b611770f7f47916a9e9cf131659a6fc49c35d1c53cb33dd7cdea244b6bcd3a4d2c2b2ab672357989b4b7
    HEAD_REF develop
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
