# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/interval
    REF boost-1.84.0.beta1
    SHA512 27fd77e1a13e89aaa90245d1475b4935e4ab90a8439a4ffd3576395b1798758a8c5eb108c58608b0439ad1fad2997517c3ac5f3e213a0908dbc21ae7da6db957
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
