# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/serialization
    REF 897dec4c0160aa683e6f4720cd1dbd93e21e786b
    SHA512 7ae4d7ca9cbaabf9d3973e9601ce0fff12a528ca74449216dd24fe57abc1484197d8f5a6725c4ec6dd8c8b212a632084934e87d9d4213e215f0801eb28cb3113
    HEAD_REF develop
)

include(${CURRENT_HOST_INSTALLED_DIR}/share/boost-build/boost-modular-build.cmake)
boost_modular_build(SOURCE_PATH ${SOURCE_PATH})
include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
