# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/utility
    REF cea4262e623a17abf17f964fa951e218320e73ed
    SHA512 3954e2f19205ece5bf9ddce759e8cf2494bbe0f26a87e2e03fdcfb110c348c41e7b201015f1fefb24753c4b2ab8cf562487816e232bc5a89a98cc4c52928dc6e
    HEAD_REF develop
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
