# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/utility
    REF boost-1.84.0.beta1
    SHA512 bd6f853e18b1b3fdfd97b539146a63bfc333be5c106315eeab0f5d5fb27cf2565e89db5f8b76a15562dcb4cc660fcca9c0f0c203208e3025e10cc57940fb8b77
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
