# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/python
    REF 47d5bc76f69e20625214381c930a2fad5765e2b3
    SHA512 9c3eaf77d70402498c347b5c027e0b05b3b3b00b58847493526e2c9566189e84fca66a828d42727d475a230a7f7cbfa2ea80473d1a0780aad02b6d2ac2152697
    HEAD_REF develop
)

include(${CURRENT_HOST_INSTALLED_DIR}/share/boost-build/boost-modular-build.cmake)
boost_modular_build(SOURCE_PATH ${SOURCE_PATH})
include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
