# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/random
    REF 3c1f0dbf634ad92fd2a2ffe2a46f5553e5a02de7
    SHA512 b1e45b7699c891deb10b48bc3b5d9e420926f89dc37a7900b3ab9edd892dbcb5f3840ba345155d03402a8fcb22102f9340689d8e4efe2dc17cf697fb8631797e
    HEAD_REF develop
)

include(${CURRENT_HOST_INSTALLED_DIR}/share/boost-build/boost-modular-build.cmake)
boost_modular_build(SOURCE_PATH ${SOURCE_PATH})
include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
