# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/hana
    REF boost-1.84.0.beta1
    SHA512 894e0c2870d2a904a90f64f41ef60b70739a4ad5873ffdbbb343d302fe8a4eb8d3026155173ee3d5d76b6f603e9234e7766039095750bbf754bebba3a4dc7b77
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
