# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/array
    REF ecc47cb42c98261d6abf39fb5575c38eac6db748
    SHA512 3e22bfd7765cd2504d53ee94668c9f62988eb3c701edbde455b61d0987577006f220bdd480a32970830364cfbc87ca83176948ffe4a92858c12c6954b010fa2e
    HEAD_REF develop
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
