# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/container_hash
    REF 226eb066e949adbf37b220e993d64ecefeeaae99
    SHA512 7bc9319e3c1969258f82c4c407a19874b0be7f187a42c72525929cd328dc496c4620c70865a5ffaa6cb234ca67248aaad8562417139777b4710c00620dd03fea
    HEAD_REF develop
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
