# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/container_hash
    REF boost-1.84.0.beta1
    SHA512 aa8d2aa6c98cd4b489222dbd2dd126503648b6dfb374d81394df96838c4b195fa67e5603f053cac426d497f79ed7f98011b347088f0bc3dc56b056721e02b91f
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
