# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/uuid
    REF boost-1.84.0.beta1
    SHA512 fcd24ea5665bdb422a1908dd6f7f9101d5b18f46d37ab8e6b033cbad553647d3d5a6072702b58c2a08cb9a06e33a6cf81128377809fb1e1ee953c59a06920a25
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
