# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/ratio
    REF boost-1.84.0.beta1
    SHA512 1a17e25ae56dca05f6498595df26ce397cd3582d75e3c72d6eeb105fbf0d7d67b782e96ed1ce0edcdf9bc008a10f0387879d6dc569d56454688dd21cb904d168
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
