# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/lexical_cast
    REF 1ca93a8e275c88efd83b3d622547faef697e0f42
    SHA512 4288d8610670da7f64da4ca5e7369126bae519fe55f19928e38b251c93e96e9166d4c47fc10f6bfc64c69cc1c3487c8fc5ea8bdb5e24dad84d57fb9993194331
    HEAD_REF develop
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
