# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/asio
    REF boost-1.84.0.beta1
    SHA512 1807fc3858d66b9250e11018763e72eb56438e4d5158e040942b9042b75b7dd19cb639641bd559a08132fc25a4abfcd444ece8bbf3a539556348f848a6348579
    HEAD_REF master
    PATCHES windows_alloca_header.patch
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
