# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/asio
    REF 28ff1e7c2b44f141eb809abaf2d76c95f38350ca
    SHA512 ff3946ffd676825e2d1d6b1300752e5b358a9f855cc84383a218f7206fe734da916cc6d116694bc91fe1850b6a9104195fd09ca3633ba5eb47f4042b7bf2962a
    HEAD_REF develop
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
