# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/iterator
    REF boost-1.84.0.beta1
    SHA512 826d532c573233ab503e12cd2b7d86038219580090f074f7401708ab4501cff4cdc7d6e0a5576709dc99e5e87655007f04fb35366efddb08de2e24b8dcbb0a23
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
