# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/program_options
    REF 847b130e19a9e5118bfb5486e9b4d4f6ab2797a2
    SHA512 4e572864d7baf77e2390c18530e9ee4586d2278e0356247ed7ce5620668b6a8343e292d8cbd3f6afd219d50f2c03f2774f5e4143e5fc36753ac894392e950419
    HEAD_REF develop
)

include(${CURRENT_HOST_INSTALLED_DIR}/share/boost-build/boost-modular-build.cmake)
boost_modular_build(SOURCE_PATH ${SOURCE_PATH})
include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
