# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/variant2
    REF boost-1.84.0.beta1
    SHA512 05c668eda4ee99a1c0c2f424253018c29ebf56d85e367280b5fe78a7d29cf0bd2b5fabd1143efaa5de022a08a00ca321e048c7c5ba94177c751429adca44d389
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
