# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/msm
    REF f932a51ef0f7a136312c7d2949fb69963cb46830
    SHA512 d9e7d887f85025d38c3121fe9b0f1a59e5e21084a30f71976924b0ec00d25b26e4b5eeeca782c5fd77bb689fc42fbce0a6432987307109ef8e79b62755c0c97e
    HEAD_REF develop
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
