# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/msm
    REF boost-1.84.0.beta1
    SHA512 c83fc7d5da52a1fd93915e992c3747e7135ebee93f0d77ab2c89547a4478458b4d75df980b102715f02c7c35faa5de50a24caa355914ad520531de3866c269c9
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
