# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/intrusive
    REF 060a6398c768c1091400ba304113fccaa64b79f3
    SHA512 7a46d9788fcd66890d7e85954cc557ea765f232d1c60d0bcb632ae616bc62d6db442dcd16a9e7056f3b2fa0b2b98056e9e4859738b04957a371127c7e15fb55d
    HEAD_REF develop
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
