# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/parameter_python
    REF boost-1.84.0.beta1
    SHA512 7b9739d425ac269944049911c6e2c8b5406d686c8840422e4b790955d9780efa8e679b0f5175627e1684b2dd0ef4352fd7a9513ab9a476f250daa5823b88b821
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
