# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/numeric_conversion
    REF boost-1.84.0.beta1
    SHA512 3ed703321c2da383c391e9266a403380d237331df28cea320a995ce390360cd9e75594c2200dbf25204dc4b089a2c55cae27b72bb0f90a72b3432fb0345d65af
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
