# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/coroutine2
    REF boost-1.84.0.beta1
    SHA512 a854a630d0818bd3204333e78a546c61e017449f5bebcf3ae779a2b4bf096511b2f70655987ef18fde6a71019dc8fbcccf2e8921fa86bec77fd4b4fda5bca723
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
