# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/scope_exit
    REF boost-1.84.0.beta1
    SHA512 f14985f27b1b839c52578af074f96420ab21f052523dcd91f7424f126f662f7f8530763308c49799d030ca44911a14e3746e8ef380a4439d1d0da46645268f0f
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
