# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/units
    REF boost-1.84.0.beta1
    SHA512 ec068a6b2ba3b22293b9628dcdbb931a80f26b309738347174f45e9a1d5c606340d55270049f96cde1c4b6e2a93963b0ea3dc1542ebcad13209c225499a2e1f7
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
