# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/move
    REF 60f782350aa7c64e06ac6d2a6914ff6f6ff35ce1
    SHA512 13f4f7246d1187b17cfa322dc91dd6224afd85b6fa8daf2bbd9e9db297714de1f096ce39bf510950a2996067609041d32e9350d24c6ae965deb70ef426990cad
    HEAD_REF develop
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
