# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/move
    REF boost-1.84.0.beta1
    SHA512 1ca7f06e7d1ec29d7a85cfa4696a1fa5781db05726bc3bb562b8eeacdd4233b2ddd12aaf841b56a15d1663ac081e05a1e9583bf3e2bfdaaa2a6bb2ae9025ba3d
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
