# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/describe
    REF boost-1.84.0.beta1
    SHA512 adb51b88e77c62622fda14acca6aec0370f047d2241d7ecf0d78a6bec5e04ddfa15dbbb49db3e550d3a2ced31e525f2a25015e2e3548f4561fe1c1596529101b
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
