# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/describe
    REF 3047e5a72f2ad4650d0b6bbb58932480243d2c5f
    SHA512 2f2b8064cb89092ef4e1e61777ec650d44f791637b1db29a3ecb1207a8aa8bedb1acec67b7d0f7ea9e35fe7f6880f3d0ef81984a9283d5dc08f5b965eb340e7e
    HEAD_REF develop
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
