# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/crc
    REF 96daae9fcdf965298077ed12a9304ea24713bb40
    SHA512 27bc8ebaa200f72d7e59ce2308ce359716ecbd78abf08ef2679494438cd47eec67c8e26d21bb82d403d9f7272e76a7d2253f63f54891046af0a0bd78a62f0a05
    HEAD_REF develop
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
