# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/crc
    REF boost-1.84.0.beta1
    SHA512 b59c2aaf56ace736aaff575b17f445dad95be34e8d424db2d4a294ef475f2fc58270368c9090feb6683c65ec7f27985cbc80a2c4a155e7c1388be629082754f1
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
