# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/format
    REF boost-1.84.0.beta1
    SHA512 9b53eb68425500b40ec9aa2ecc2d018187b1f09cecd1122e069894fb15c4e24d4c446f33a9446f062c337709d7290a22c12181df142ee8d012ded149cf163922
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
