# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/proto
    REF boost-1.84.0.beta1
    SHA512 fae4994f243f488bc9f8db567cccb534bb1a68312b99cd4dcf252324f95f6f56dbcfb131e35ecd156e92414e3883e0d9c042c4a785379226b292cf66fa487e6b
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
