# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/regex
    REF 237e69caf65906d0313c9b852541b07fa84a99c1
    SHA512 6a57c9eb6dfce1630bb79f0c7f6e2dfb073a617f685ba371b13cb1e07949d52b29ff0e91bad6a9dd5b97f11c00a3489b49dd968319e1c42693d38db606ef5b71
    HEAD_REF develop
)

include(${CURRENT_HOST_INSTALLED_DIR}/share/boost-build/boost-modular-build.cmake)
boost_modular_build(SOURCE_PATH ${SOURCE_PATH})
include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
