# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/leaf
    REF boost-1.84.0.beta1
    SHA512 e31cad98d5f0d82688c53fecc3e61b7f2c39065c3c3b174a4a6d0a112a0ce9a019b14088368388999cb42cc02d5b0ddb3d9efc3a8af1b0a7a4fb60c8ec97a719
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
