# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/leaf
    REF 3199f4757875ce9a6ed8dba4f9e065029d79d925
    SHA512 8055bcc9766e214ac8f9c908ab8f09ce32326d378993c9eeafb2b28f9fb8470f0a12751d537eb14aefd462d183830fa06a07828dcf5f0f7c2e838f7368e49069
    HEAD_REF develop
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
