# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/xpressive
    REF 4679fbd23f962bfa78d44acf5fa48f6f790642c0
    SHA512 577d18ef6756037afe6a90cf40a265b70691122df6f141198965569446b75bb9a0d759b3fa03ef6b0de2c15f1a014e60a95481fb7fd9903cc50f265e110736e2
    HEAD_REF develop
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
