# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/xpressive
    REF boost-1.84.0.beta1
    SHA512 74d848b2fd8b7a457a0945ee8e45dff89eb26b0f94f4432d9b3cef47207859e6c12d615e294f7e8fa79a7fbf9f7b69ceade79caa38b505b6d58ad9094680ae27
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
