# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/io
    REF 83e927f998e83a29be8fb033389110affe8787f5
    SHA512 76318b966e0f2fb3d0a1c9c0f6c9c41bd2bff557fc9014ae17bcb5888968448584385fcf6840b5326983c6327ee1eca4de73b43b351b7cc28d052c0d74a75bf6
    HEAD_REF develop
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
