# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/assign
    REF boost-1.84.0.beta1
    SHA512 37811093a4a9f941efb81b16f9b2e19c12cab60354f4bcb36dfb17c66e53c6fad6f7e3784e79eaa3dc39a710b6070246bcdfe321235c943957f861e25a5d1fdb
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
