# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/range
    REF boost-1.84.0.beta1
    SHA512 511762e4b1b6f3d29e3cac5772c66b133636b39150dc6f1258d867d5c34281e19d31291509d244c4ed7304ec79a364029f52539de4e6981efddda943b9c5aa23
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
