# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/range
    REF f0e109312cab295a660ae94b138cb5f8fc7d182f
    SHA512 a8250dde866ebddecaeb97ba248de56e3cf8401a18fc8ba9c0adcf1a2636267483ae15d3d1e550d86260a133e5365a46e12ce10511f600fbfdf319afcfd68a08
    HEAD_REF develop
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
