# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/fusion
    REF boost-1.84.0.beta1
    SHA512 f9211a5e415319cd4cd46172bcfb388b7ffe8bcd248619b2f83db1ec98289536be000fe54d1e42e0402e3ede926287e89f3ffc1f7b9476ba0b33baa8add88099
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
