# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/fusion
    REF 7d4c03fa032299f2d46149b7b3136c9fd43e4f81
    SHA512 32098da201f678f72a4894790310608cf6d6a2eb2f46c0109c0b002e28df1ef96596dc0f41db30ea603fd1854c8b902101a3ba7dc7b429fd25a84d79b22e8f4d
    HEAD_REF develop
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
