# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/hof
    REF boost-1.84.0.beta1
    SHA512 f7e10347f122f0df61dc8b8c43dad5b10e524190c23977f0bdd81654a8ed59030adfc30094d141af816bfe163194eccbbc1715d5845354289240b6752cec896d
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
