# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/histogram
    REF a29729e6682652800b06dc8aded29bbeb4acea61
    SHA512 a16645fdb2e172fdff360d2969eaa6c4bf0fbb579e5eb50d4dbfb4bbe2b10f216d8d4d033f6005e280d0872ccbd56d3baba25f0d280d4cef00e71e147035f4cb
    HEAD_REF develop
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
