# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/outcome
    REF boost-1.84.0.beta1
    SHA512 daea64b982727b3a4294554d774baa6b030688b8cad6bb0a33f589f47c84980caa15bca50ba1c2f882694bbf535325e1e20710e55058bcce8d10cacc5e09cc50
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
