# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/detail
    REF b75c261492862448cdc5e1c0d5900203497122d6
    SHA512 c8ca12523d3340ae40405294e5f29f52ffaf0a366dc49c6b888c9d2ce409d4ce3ccd12204bd76ed93f57306b011e99b47237cf2033653d450151c1bef7a036b4
    HEAD_REF develop
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
