# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/detail
    REF boost-1.84.0.beta1
    SHA512 2c6444bda6746de3a696c3ed223fa107adae5b8ba99feb5a8de80d7c8c0f7b4d210bf069c1096ec77961ecb9d743d4e80074caa3ad270b0cb3958e553946154c
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
