# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/spirit
    REF boost-1.84.0.beta1
    SHA512 c6092f77cf0113301375f596c2cb9f05ebd19ce0e341d58ba88df298755578ea37ad14a8fb11a9db83cffcc7ffd18843057814ced1615d0366ccf6667116fa08
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
