# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/spirit
    REF ba5026b191fbbea77d25609406b89ae678817cb9
    SHA512 111e1cdca7097b4059248081028d7a68d74c94d371ba429680082394b86dfd71bfe11ffcb4908a9229909b23ee90931b486f8cd4657839bf28c99f1a9734dcbe
    HEAD_REF develop
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
