# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/function
    REF boost-1.84.0.beta1
    SHA512 dd771ba447a3479d12273cdbbfe7c7e506778ba3c076b08d1cc2f005162bb7755ee955422064300ae293dbf5905cf94ce49e5ff8f82f80c744866461aaa2049e
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
