# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/function
    REF 7ca2310b15e387258e97e4cd16887f5ee4906b28
    SHA512 b1de0bc21b48e229eee59ea690096aafc37a1c709d810ab52ae98124841d4d4582aa0550f203c0e9f8f883e17cf094a71c3f8fc20958e30cc10c40f2f39f6280
    HEAD_REF develop
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
