# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/mysql
    REF boost-1.84.0.beta1
    SHA512 49dece84eaa53b6be19512ed531a2d9e658a1e7cabccbd7cf0fc309a8c8bb3fc48e836bf2687f23bcdcca7625e3bfafa425dfc8fbe9e923db04a37d388c4eff7
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
