# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/mysql
    REF f410967587790744c9318b9238e7fc0d65d2de48
    SHA512 3358e2cf3b96e45135416315be989f15569539ab776ecdb40939d06b933797860873630787ebf4e87ddadc5509c7d7e3287947f517d1f65d02f82d054f0f47f0
    HEAD_REF develop
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
