# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/url
    REF boost-1.84.0.beta1
    SHA512 3cb3f3b1e9f2ebbd4846824c641aa412e3680488fbd402e98ce0180589b657e57523f6d243005adfef4c8c733c5124218d30f24d25730b9542f5d70fca625709
    HEAD_REF master
)

vcpkg_replace_string("${SOURCE_PATH}/Jamfile"
    "import ../../config/checks/config : requires ;"
    "import config/checks/config : requires ;"
)
file(COPY "${CURRENT_INSTALLED_DIR}/share/boost-config/checks" DESTINATION "${SOURCE_PATH}/config")
include(${CURRENT_HOST_INSTALLED_DIR}/share/boost-build/boost-modular-build.cmake)
boost_modular_build(SOURCE_PATH ${SOURCE_PATH})
include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
