# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/url
    REF 1dc789839f34f9a13451c3aaa5bf4cacec04fd78
    SHA512 1162310893bcef717e61d49a85d2b90f0fc020d2d3b6136284659acdc8bdff90e8ae4a0acadd90958e06f2e4add1cdb7e520db60f5787e2f00d6a6f80a1f392c
    HEAD_REF develop
)

vcpkg_replace_string("${SOURCE_PATH}/Jamfile"
    "import ../../config/checks/config : requires ;"
    "import config/checks/config : requires ;"
)
file(COPY "${CURRENT_INSTALLED_DIR}/share/boost-config/checks" DESTINATION "${SOURCE_PATH}/config")
include(${CURRENT_HOST_INSTALLED_DIR}/share/boost-build/boost-modular-build.cmake)
boost_modular_build(SOURCE_PATH ${SOURCE_PATH})
include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
