# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/lambda
    REF ac26514243521513d33be23aaa92a85b858ddf51
    SHA512 6d83a95bf0687744d676fe476e96ac7dba43644d6b07362f734655849fc2c7ca781f767af7a3da14c9e087eb369e46dc7b6c170bb54aac5e401e2bf10629b628
    HEAD_REF develop
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
