# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/logic
    REF 145778490c2d332c1411df6a5274a4b53ec3e091
    SHA512 76e00cec3f67738e2988b0355d559261572c25e3057b4303f434424d96c3d24e85e84bd9fd0f449697b1bbbcbff03ab45e57a5fd4e7bbd6dd68d5ddc09897678
    HEAD_REF develop
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
