# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/integer
    REF becbd39cc48c312f4b8ad546ae4f4557d338a921
    SHA512 f67bdff0ad102fb63485f5158ccb5feed6c547139cfc590e3f4f7f41fdde5fae582131f094272719498123ce903f7bcfc0adfb53a2126d7dec418692e1d789f1
    HEAD_REF develop
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
