# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/poly_collection
    REF boost-1.84.0.beta1
    SHA512 7432793c485a469c04eb8d0684a312c7adccbd5763ad8fac1deb262ff9da30bee1dc5a8081e7011232fb49eabb7c9b4c90fd087025ec2e5bed31805f2a07bd02
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
