# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/beast
    REF boost-1.84.0.beta1
    SHA512 37764a37ded5dc1efbb17ab8d4202fa95b4c0eadc57180cffadfd0e8d3255ffda353fc7bb97def4b596eee245c44ce58e91db15853682583416a3bcffaa28faa
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
