# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/winapi
    REF boost-1.84.0.beta1
    SHA512 a402b02f2fb7b59c653c7ee0988f48c76e5b1705a49a6c4a3ed7f6d326c862a68a59e484805fc12a50dfedda06bef2c9cb881d908ab5eb358bcbad5f8fc43710
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
