# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/winapi
    REF 02b4161832e7ca5f78e996967a793120e36b22dc
    SHA512 c31ace8f2da1687573d07c50ef541c7a78e459c6b7172100c8f991d25a8214bae7109e4707e94dad2dba86d869cc468393b9e9ed592aa96530097ccdb2873d43
    HEAD_REF develop
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
