# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/lockfree
    REF boost-1.84.0.beta1
    SHA512 d0098f921112156811c3f83be70dd2000857d381bb1471dd64e8eb6097cd65e29bfbd8afb757e7b880f51648098e3c414dcb84f5c2a09d613442b07c40a4b03e
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
