# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/lockfree
    REF 417fcdb6e79654338cb18842a16007bb55b08aac
    SHA512 ed3d86d5d7fc2919949b7ed65758ef6d27f2f84f6e391c85365e38d3f6af631078ec8a36d258c9b4862b8474067904a008f55a58fb1d93eac290bc2523b67c68
    HEAD_REF develop
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
