# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/gil
    REF boost-1.84.0.beta1
    SHA512 8a78dfe233664b8f55d9eff4f0868aacf43a508a9eb38a29b7abc23293081bdff9af815899e018a49cd92bc2b323fc44f71ed2d88cc82d9ce17db460963451bc
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
