# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/optional
    REF boost-1.84.0.beta1
    SHA512 bedde52f345c167111b514e8927089588b2782636308a82fa50197029845127c1686097a386d3abf9e1c7b3d2589d510012d7e3eac264fb8fc0d40e2aab2fe6e
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
