# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/bind
    REF boost-1.84.0.beta1
    SHA512 5d646e1ee0557602ddb1ea032796343773e54a9b1e30da8766d40ae62020a73cd4fbf4029f3500cdfeff8abc44c3be05050963fcccd28d13b48b1934cd5b0bb2
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
