# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/bind
    REF 55d037093bc715d3cf5682f6f84c3dc3456a3b97
    SHA512 44ee81d0097ed1e4f3095fc8966a1c9a89c7dfbc000925e243909c22d20f89d2326ab1725a2440c40b58c8c6ac994c8bee887a82b8fa4d1c33e82bd0fd18393c
    HEAD_REF develop
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
