# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/parameter
    REF boost-1.84.0.beta1
    SHA512 8f2572784e83bb78ca285cc6a2b28539b3464c0b3db67b5ecd0758540915c478553a78cb553374b3bc6939b7df50b53c18d4994caddeb3bd7a002f5fa7cb4725
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
