# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/dll
    REF boost-1.84.0.beta1
    SHA512 6e02006bc67f9bcc06fdb2e5dbecdbf38ca7553bc32225827fdf1d37b333d03a5af32190e41570addb90fdd99ca72e2ce40ace2becd9f7e6b68ac173802acf87
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
