# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/compat
    REF boost-1.84.0.beta1
    SHA512 241ced1fdcc44734416c0318730ab6379e17706cd7539ab780ab3ec720648f68342fb0c0bd17308adf51a0008dbc2c1e416b681ce410230a435c28f58d100493
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
