# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/compat
    REF 0008d02a6211fb598b8f76c4edc92b949150fae4
    SHA512 faadc0bc3c3de3e6b5c4b02107f5c07b422d792dc33b0910d67397c6e3d05f3f4c80be868795b37a6b3b92791d2a80871c5ef73eabb09d7fcbe7441e2009bc42
    HEAD_REF develop
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
