# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/rational
    REF 564623136417068916495e2b24737054d607347c
    SHA512 82a999a4483b6e611612317f0551be41024a490153f4fa74300ee361bff76fb114f0a7c95071a5a83dbe166a33ed7768d9173ca64ba786507bed388366546e14
    HEAD_REF develop
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
