# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/rational
    REF boost-1.84.0.beta1
    SHA512 069416f49274df77b643dcf58895ee17df33521424446af3ddda09a7a4e1e6df3089716b6fd6b69723619152e2ac1ba6eef158b6f23413ebb1ca89b5e084c480
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
