# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/polygon
    REF boost-1.84.0.beta1
    SHA512 e641148446a8bb634c91ced89b03cd1c0003218c79c2af6473b3d8772bdc7dab5a7f4ae38f24e4d7c3d3d788c38e1fd223c2ebfe7fd91a34a7479f3986c05bff
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
