# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/filesystem
    REF fe07038a2d245178630eb38d255b555d6d14966e
    SHA512 a6887bf6a8f26a8744ff9568f22e6e45396819df43f7e673876f07cf88164cf5abf7c834caff16fa6b7ffbbd7719ab5bf0175602e914b3e6ca52a3336d8ce5d0
    HEAD_REF develop
)

include(${CURRENT_HOST_INSTALLED_DIR}/share/boost-build/boost-modular-build.cmake)
boost_modular_build(SOURCE_PATH ${SOURCE_PATH})
include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
