# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/static_assert
    REF boost-1.84.0.beta1
    SHA512 b498d1fae05742ef1fe9eccae1974a17eef965ce16545f5dfeef4ef21ad3e01ff117c355dab0635deccf4ced2c1e91bb0fce95a30104625f524b9a0983a088ef
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
