# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/endian
    REF boost-1.84.0.beta1
    SHA512 e10c51d2156ba46eddc9126a09032ed0775673a4121b853e729049e95ac5f016786f1948507790de805c8c937339d826eb0c37df47c5d6d2fe2006bef588612e
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
