# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/conversion
    REF boost-1.84.0.beta1
    SHA512 a9c0376f3c9eae4752dc1644534623591157b8a20eb96603fdfb353dbe09bcf88bb67bf9c554b11fe90e514619316d1cf486373e9acd6840b6769f24e7d88683
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
