# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/static_string
    REF boost-1.84.0.beta1
    SHA512 438dbd0fc4c061a5b4367b99958c961a9edd77f288baa893c90075fdf3f7694d38e328723e99cb7359e2cadfa14dff1fb8e2c5be740aa146be362eb0225e0de5
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
