# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/static_string
    REF 175f467a03841662c0aac7442978245b977fecf9
    SHA512 989825369ed9902bf5922ee77821fb275317837b8d7d5e6635aa85919164bf6b2c8801149efbc02bdf84b59ae507630d982f710924f30605d9b2a6a1592bd153
    HEAD_REF develop
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
