# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/variant
    REF 9d1e62f33cf75486fc12ab11aca9a3036623119e
    SHA512 700486d5607f294ffebe61eb2a516024df77d6d27c7e6b185044eaeb4c109bac1b8ba8db5203c74e0c6fd5356bc35f4a647decd0679bfe9c4a1118249efa8afe
    HEAD_REF develop
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
