# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/variant
    REF boost-1.84.0.beta1
    SHA512 a42cd0eee2dd374fb379f923a68a891c1655ea463cdbda610180d317cf8f75f246b819d3ea620c9b2f9a8b284517a1a51919f355dc069a0c0bd2a0102a5cd2f6
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
