# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/locale
    REF 2cdef1a6f97488e7827697a6201da5239051c9bf
    SHA512 a690090e5adefd2972ccad22a4cc9a04ec6ca56e0aaaf4df286840abf6372c35d1f9eb032ab4a0da4e30a08a80a050001d4984e6399b0f6d6a4a6a8bc6339e77
    HEAD_REF develop
)

vcpkg_replace_string("${SOURCE_PATH}/build/Jamfile.v2"
    "import config : requires ;"
    "import ../config/checks/config : requires ;"
)
file(COPY "${CURRENT_INSTALLED_DIR}/share/boost-config/checks" DESTINATION "${SOURCE_PATH}/config")
include(${CURRENT_HOST_INSTALLED_DIR}/share/boost-build/boost-modular-build.cmake)
boost_modular_build(SOURCE_PATH ${SOURCE_PATH})
include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
