# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/safe_numerics
    REF 13ca3d6dd36db1aac2d6b5caca2c281d15c881ad
    SHA512 a8c2ad08c2731282727387d7a56bc3319f9733f0c88fda205012da3e7a00ebd8717ee7e470f576cb0bcc754f13234493e71f64dafaaee5413ee44a2c53769c96
    HEAD_REF develop
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
