# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/assert
    REF 02256c84fd0cd58a139d9dc1b25b5019ca976ada
    SHA512 5dd0b7145bf4a978242f5ae56c38e04b617e4e80fec29330ff3da33802b0979154daed43c365bef64444caf0630223050e0e07b5b683beb903b6a0a68a22068b
    HEAD_REF develop
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
