# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/assert
    REF boost-1.84.0.beta1
    SHA512 9d403c55cd869b12218ca9fda81f98d46c6629fe538ee1179f04549f64337678fd6dbe09b9c0224c927cb519e9d03ddb0923985402d81d22326e604378fdda09
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
