# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/multiprecision
    REF 737357f1fecef5c6c6553d4dd280f47aeb056aaf
    SHA512 733715c7337105e11bfac12b534dfe12607574e60bb2b5d055795f6aa2b991b9dca023706d474458a6142f1c10e94106d128e8649e4e132225ae5c306d6e56c1
    HEAD_REF develop
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
