# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/multiprecision
    REF boost-1.84.0.beta1
    SHA512 b072539a96e7660ac9d32befcf02012dc6b4261c840ee562653bc2a4a2c3cf11658bf9af71e821cb68d84fb15ce7b8890b3f4883892dff4e4e31ddafecc4391a
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
