# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/foreach
    REF cc2f75ae30492b9de69b3b692f5c59afcb7dea5e
    SHA512 80ae61b73bc8d455dd55ca968a8a83223b0897f734b62c2fa4ae23bacfb08b05f2ba7d3d3938ad1e0ec8bb8d2e10fa1256fecfd6431e9706df7f10746ee72d4b
    HEAD_REF develop
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
