# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/foreach
    REF boost-1.84.0.beta1
    SHA512 1f403a3e32059d9f69c4c664e7de605c5d576108ac2f82497fd17b0e4dc592d20ae8d56fb87ca2c7f160090d1c4ce474bcd38f1da7d176533c3c37c7ec93ce44
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
