# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/pfr
    REF boost-1.84.0.beta1
    SHA512 bba9be7188a04a4502041df6fa49c3c5678c5cd507c4e544846d9c3ccaa4bc86fed862153e4e1d2ddecb46d69c8a251f36619cfed7d8bf06ce46479c835fe1a5
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
