# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/statechart
    REF boost-1.84.0.beta1
    SHA512 38d5d21dd054ceb45bdf33baf462ec655ccd007d6a5ff3a880a4378af3638d08110fc0aee1c94d5519bdcbc8d2ca64aa6f7d28c7e2d554b83facc920485e85ce
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
