# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/statechart
    REF 586445b824c5cf0e7e6ce4ff2df620fda5d0f0d7
    SHA512 4e2386e11e6c085def476bb5089dbb68520aa59327aa10a6f5981fa301d38bcd42a407d506d4bbecbd373f8aa45752171cbf509fb446052022002adcffd97d87
    HEAD_REF develop
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
