# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/ublas
    REF boost-1.84.0.beta1
    SHA512 599f7ab7417af1e48fda4948a277199eb643eb7be46dab6fff29a183e0912805ee2ffa53f1fcc6bc57e6e1684d545bee8786679df32cd10fd7cdd40497a21035
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
