# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/ublas
    REF 3a4fe24ee16b4d6a084eb51c37cfeffba697ff71
    SHA512 792def0d6272d3b41a28dca6cac19045a0f7906c4007877a87ed05a02fb196ce5444a9e4fc048f7affd6db819f844930609f6af3e942ef758a87bcbcde90a256
    HEAD_REF develop
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
