# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/qvm
    REF fa272cb0b07ce85b5d8d53fb3dfade389e9cc4df
    SHA512 0c800b65f463a7f286be82ca362fe92eb32fec130bb317b7683ff823b30ab3b0061da04ec63f557b61809890bbc9dcdad610a9a015391c6fead351ee6626e3dc
    HEAD_REF develop
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
