# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/bimap
    REF boost-1.84.0.beta1
    SHA512 bcbba0ed1b5dafa3908c4bc94842692eb7dc4dd09df6ca851764c2b1bf90f922ad42745f87d4713f3443f7d760a206afc01882e527de7f4de5ee0b56eb0d8e9b
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
