# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/bimap
    REF e5c2657a9e2d6184622ad4ccd1373e6c60a7efca
    SHA512 102e4bbe01d03594e69d98fe5b961b2fb5d43ddf7df75e2569913559a20c4e9ecbef373bc5d3c18c9aaf8463f5aab730a3488ae5fe422b4b9e0784e62762439b
    HEAD_REF develop
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
