# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/compute
    REF boost-1.84.0.beta1
    SHA512 add70c1e6a5ffdf170cf25da2e5a57749c2365a00985cf420208dc64e78510c4e91a965f5d258b322308217883ce6e873ba3458ee48273d0b260ad38a0c8179d
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
