# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/vmd
    REF boost-1.84.0.beta1
    SHA512 356d3ab4ee8dd43065b2248ad2909bb8aac800471f494153c218a72642d802b08687075ddf24369224dcbf1e593e3ec0ca64a3e855ac95058c56c6b069bd2cde
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
