# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/circular_buffer
    REF boost-1.84.0.beta1
    SHA512 65bcc0bc4c5faf902853fb102ca5786e6d3dd71f91734d75846b81b9b2ca337a56d9dc16ac07e63b12c1232bc9528397268a05be85fc3b05242465014bf38315
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
