# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/mpi
    REF boost-1.84.0.beta1
    SHA512 1c66f0099f35961ee18ddc0a3b50cae37549627b2717d84c406e591def74a09c8ae202dc856e1c84854cc575ac92199c3e9c9213d21c17e8cad82fa7d1b9dad4
    HEAD_REF master
    PATCHES fix-build-with-msvc.patch
)

include(${CURRENT_HOST_INSTALLED_DIR}/share/boost-build/boost-modular-build.cmake)
boost_modular_build(SOURCE_PATH ${SOURCE_PATH})
include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
