# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/mpi
    REF 347595c77379ac5cbfc6e4474fe315398fef355e
    SHA512 c639d3519fc39615e84e272977ab1abb871ff7758b5406a697e646f466b29cf5c1419b3d89e7fabd909c36b161de60ab8914d699fa02695312e936bd96136e28
    HEAD_REF develop
)

include(${CURRENT_HOST_INSTALLED_DIR}/share/boost-build/boost-modular-build.cmake)
boost_modular_build(SOURCE_PATH ${SOURCE_PATH})
include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
