# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/accumulators
    REF boost-1.84.0.beta1
    SHA512 cb78b520a4769866d20468b8ed7895e444fc75218d411475219e0f1aebc7a473ac713234479718fc3367018125e8bae50a199be2412a53760b74c5a9f1fc6221
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
