# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/lambda2
    REF 62815a69bfaf6d0fac5ace703737e7a9b4899139
    SHA512 e9189ef4c6faff0a56cc147ae73b59420a6eda61d96df5354de6d52904bb77e344c5f6acd30d40fb5359e397ab9072c4b5c897a842c46424281e2a207d8af358
    HEAD_REF develop
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
