# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/lambda2
    REF boost-1.84.0.beta1
    SHA512 beae30071b00f78db957365213b9dda384ef293c713e89e4afed796a6dacafb039c548edacf567145a95c89e20b19290eb4029af3d9a607bfb6c40a9021d43db
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
