# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/preprocessor
    REF 667e87b3392db338a919cbe0213979713aca52e3
    SHA512 94edfd50ad444806de335987ac73eafab49ba5a51a0ed4ef01711c224a0665283fd375d034a87ed7ab10b731cb785dd48c982a67294d64fd8d583b4cb48c344e
    HEAD_REF develop
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
