# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/preprocessor
    REF boost-1.84.0.beta1
    SHA512 5bcc211a35f27b92648ce60273655ee5a153fe18b08e6392ec96f6bc0d81ce40808e0735c85c718ab3427179b6830a3ae6c5ea4facf0c07c21072556939214e3
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
