# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/geometry
    REF 065674e134043f9b4b68d74242392dad1ad8edec
    SHA512 339262d27b7c3df53ad2a3f2aa1f6daf29d9b5861c61b5768fa4497d746f4d836d495c06db996914244c6d650e2de76dcefebb12db80cbc5e5492dc3c9b34ef2
    HEAD_REF develop
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
