# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/geometry
    REF boost-1.84.0.beta1
    SHA512 e4737ede8c1a228bdf70a446b8fcfaad8ebff33befa39a2928b09121963d2af5240c07542d8649097d3c8ec02c74b2afd4962351bfa204c9ed996c592b92f027
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
