# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/dynamic_bitset
    REF 8e20aa1462bf6dcadc338835df529a6d568431b1
    SHA512 a7f0a347a923e0cf5d82af73defccb8ceac3ca40830a2186f17bde71a94b62edf3f31d44fc03c5a5b6f7f1eb1d5b29316c961c6224254f19173613f46004602d
    HEAD_REF develop
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
