# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/dynamic_bitset
    REF boost-1.84.0.beta1
    SHA512 e7bb51a6c3810382ef2deecb4fed292126314413d37bafefa74a5ed4e97d0fb11a5bd5ac49b28c8d4a9ada9fa95b70ac5d08644f5efc7d9617c312ceab903a19
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
