# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/type_erasure
    REF 729f3e739abc65d36d46df470c5bab735599d042
    SHA512 ae2647696ccf965a30dc7a6709d3304ef8555441a46f1b606138bfe3290106a62543d98ab1605570fe40ed57d9bf2dc0f83ee5f0b61978a76b2d52ba26758aa8
    HEAD_REF develop
)

include(${CURRENT_HOST_INSTALLED_DIR}/share/boost-build/boost-modular-build.cmake)
boost_modular_build(SOURCE_PATH ${SOURCE_PATH})
include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
