# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/tokenizer
    REF boost-1.84.0.beta1
    SHA512 43cd8dfe4204b52bcb279fac85444a02cb795188767bf70a5fa917f894a21b72e638ac8eea7b8363be75a60dcfbd686838d3eb63abc6c2037d3395d33b8ddbfb
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
