# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/tokenizer
    REF 90106f155bd72b62aaca0d9ad826f4132030dba0
    SHA512 746745f5ceb59c078648958dc1fa0480b71b45c89fa73a4e0934358db4c6d4e3459fb71c804af8c0a5c460aa55b069735006bee4a5fda97b4ed446a6699ad2d0
    HEAD_REF develop
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
