# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/process
    REF 507768e2308f3e9935f3d1d0eaaabe9f6628105d
    SHA512 0d8efc57c521bf93c8092fa94fc56816270a8e6b2f32e503fcd704f1922b62ba8db25b2090ec47319faf6bd67ec27bbbed78f5d65411e64e1354e893a6c87f7d
    HEAD_REF develop
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
