# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/process
    REF boost-1.84.0.beta1
    SHA512 a26b79bd89430593d0a35e17659a0f05fd0970094f8825b730a1b8489a93a50309da75ea7ed2d2c18c651f8784ccf03bcc837a38f4855d0dab332f295bc555da
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
