# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/coroutine
    REF 1e1347c0b1910b9310ec1719edad8b0bf2fd03c8
    SHA512 7d5420979b2b040810b9af965c10d68a9b393dba8c83a3de21cf251d739354d8de74b547dcf6228e781b38e121430b18224569f939af59a00e23e34c0dd59097
    HEAD_REF develop
)

include(${CURRENT_HOST_INSTALLED_DIR}/share/boost-build/boost-modular-build.cmake)
boost_modular_build(SOURCE_PATH ${SOURCE_PATH})
include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
