# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/timer
    REF 85b2642a42e55706c98fd5227be162747547aea5
    SHA512 e34b3931f88998158f7f1d1b31f584853b60101b5492187f0a2c1f6a31ee16fcfe284abbbd254dc96b4a95257f824acf85841f93a70a0719360456df2dd87995
    HEAD_REF develop
)

include(${CURRENT_HOST_INSTALLED_DIR}/share/boost-build/boost-modular-build.cmake)
boost_modular_build(SOURCE_PATH ${SOURCE_PATH})
include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
