# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/convert
    REF boost-1.84.0.beta1
    SHA512 45e6b72300743ba5e65f5507379397f095fabbb91b8ae000efd17ab3d2b3b2e907078bbb42da6a28034e750fd6dbac1d62048f04e28c440cddd422889242e32c
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
