# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/typeof
    REF 8c654f75a36a4a2cdbc1f79f4e120e1fba856ac4
    SHA512 a0cef3b6cb3cc3e04b4a3767082f079323c0870d937154cde478b20597e966b589e9e80cd24cabbcf0f0351653f7a0aabc07f69e890b59ceea229020607dcc65
    HEAD_REF develop
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
