# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/typeof
    REF boost-1.84.0.beta1
    SHA512 85c228489a95a94f53fce9cc6d4679605451b572ec3ab2aa2085c78c31be8507e26389a023914a6fa08781e62541b399fffa26b436280512cf56a3e0a50ea2ad
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
