# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/local_function
    REF boost-1.84.0.beta1
    SHA512 cfe4df11e9b303948feefc491211986500c6b74ce93ff9c4f5ecba68ea6e88c6e61776530e613a978f3f655100361e442a9cff915e438658db9b5d15ffa2fc25
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
