# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/signals2
    REF boost-1.84.0.beta1
    SHA512 f4fde5c5267e5eb0b57b0e23d3cad17868b8e166181ef64be4098acf6fd6fdbfdaaab6441c4c1ee77294fe0da866eb62fe6313f267f4416e157861400ea2f88f
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
