# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/signals2
    REF 9bcd76256a76a0cb89c5e0f047a8386c230e7b78
    SHA512 0cefb6f512f4a6791328f9b80199681474fcbd9818074fba5401eb09a3bb4c0026d138f015e69494d829a1a2387355dc46af59768fcb61b299b98b8fdbf8b841
    HEAD_REF develop
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
