# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/pool
    REF boost-1.84.0.beta1
    SHA512 e06067e6eef368e0ae92dee27bfd6fc2d9843e02d3a155cc251aa5575e05d8446725fe3e35599f52dfd0d8b3d7eb80ec2fc948ca6395be873938f69df1c2cb34
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
