# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/pool
    REF 8ec1be1e82ba559744ecfa3c6ec13f71f9c175cc
    SHA512 2d3e2a805929fcce9119df398f0440b6449bf7467c28ee10c97757f38b555d942f2b0a41cce873e48f162d1803623f20a4806c4b28c62c961c215f6ce110aa37
    HEAD_REF develop
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
