# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/graph_parallel
    REF 5520a5617d2763c48a06a4ff277ad76e665c7cf3
    SHA512 62440fb1dbedc9df3d045e7dfe1134c26181ce63a8352cf45fcc8f6123bd9c130923cefbe569fb916193494a10dfe300aa64822d4acac502c41241be7725b19d
    HEAD_REF develop
)

include(${CURRENT_HOST_INSTALLED_DIR}/share/boost-build/boost-modular-build.cmake)
boost_modular_build(SOURCE_PATH ${SOURCE_PATH})
include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
