# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/core
    REF 5f6fe65eb227375888f7305c73767600ab7f1cf2
    SHA512 34bd22d3a4147a41dbc7ec3871942ed74e5a1c06bfe703d2815139a7a946f13da6654a26142063f3e610634b40d10e3a807b51cd5b9d1ae05b994d39b4ea340c
    HEAD_REF develop
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
