# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/core
    REF boost-1.84.0.beta1
    SHA512 0e11b2404691f80708fc9c63a206c9fc5d63e99cf4d42ea992e125c1c8754448f0458987e3fa4dc82597164365cf8bb3cb8a55fa7987ebcd608fa0260a6e3f90
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
