# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/concept_check
    REF 37c9bddf0bdefaaae0ca5852c1a153d9fc43f278
    SHA512 46225527dc700caa60702af64ff5ad00fb9e3deb9d332b204f7946c9e5bcdfc85687fbf7c90108141fb36122536bd685c1f23ce34c48ba80c8f05415a2ecc0e4
    HEAD_REF develop
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
