# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/concept_check
    REF boost-1.84.0.beta1
    SHA512 f137937539032010231495fe46dd438d7ac58693f3302301b696528c1c433d3bc426c8a02af4006a599d3dd230dc3531dcbcad6448e7caf08f34f0dba39eda15
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
