# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/math
    REF 09d82da6e9884da86495279b331ff038dd1330b8
    SHA512 17ef968a56d6c329152e09b1c944c038bbdca0b399e4b5996cc2cb98300eaed8c497874b39ef570ab4a294bea83e4e54059d7342d2f5d97d690d6135d15c2516
    HEAD_REF develop
)

include(${CURRENT_HOST_INSTALLED_DIR}/share/boost-build/boost-modular-build.cmake)
boost_modular_build(SOURCE_PATH ${SOURCE_PATH})
include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
