# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/function_types
    REF boost-1.84.0.beta1
    SHA512 52057e7be1b7f034d12c6a7a7f7dca6d371c8ecc37a773adf88f2432bebbec9e659aee838dbe6b5d329d3aa218a21911eab430fb563e547f5e860742efa3da45
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
