# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/algorithm
    REF boost-1.84.0.beta1
    SHA512 86cadd272822969f57733e1a02a2e86d84dd75e8e14c4cacaf2b1683d9a0ffe55117e3128633ade9c45cdfdd5c690e70f07ac4ee690ffb27a16b0b3bdbafb373
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
