# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/mpl
    REF boost-1.84.0.beta1
    SHA512 59c30beb1348a77f7f564b0ffc748c59682ec73dcb040c4deb50489c7c3f0a42c23638cc02eba4a68c071f4a3fc64eeb5f0194801416eb1749762e0f236924e9
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
