# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/mpl
    REF b440c45c2810acbddc917db057f2e5194da1a199
    SHA512 63b589bd65dbc53fc1cad6b0fc0f0146c62b478cab3a56254820c299fa5ef20d62b4b9227e95970231a370fd2b418383bd2781855b853b570b3299d77ff3c42a
    HEAD_REF develop
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
