# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/flyweight
    REF boost-1.84.0.beta1
    SHA512 82d2e469d3a3ce0671d288ae9df8cb9af7698bb34332210cd0dfa3d267a5aea204b30080e846088e3576bac2b393e20bc5ce1d92604a2719256c65c1b0f4f536
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
