# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/yap
    REF boost-1.84.0.beta1
    SHA512 ce69efd4c3d65525e017f3b335bdb6e5f06ee28695e86f415177813064aeeec4f0afdf9745c162f53540c9e7eb7d81bf7663909c4cef87de73c40ba52e2bd2f4
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
