# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/yap
    REF ae49bf2744586e6bd6c0cedff4500a58a4386860
    SHA512 596680737476cfe684e59b018b338abaf2d9361e38b84cbb57e46040dd0816adc3ba64bbf7dce822dd0a17ff4ad9c28b12de61492088d06418d6ba459b290eb7
    HEAD_REF develop
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
