# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/mp11
    REF 391e23ae716aec4d59f6c7272e49e1dd8c01dcdb
    SHA512 ad3d1b233a10462b795f3f9bb6e9c41d0ca65a3638c7f5f36e9050755b0661c3be7bbfad4827aca98badd3d76a1315d2ee36dc17ea1d5fed5adad9deb36cf839
    HEAD_REF develop
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
