# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/property_tree
    REF boost-1.84.0.beta1
    SHA512 038d348abf980a14336f6ab6dd44325d4263383b86794715ca5f77bd16892e20094d52ac08b2feb8d85af6712ece8ef758e823bc5da14031a2e24bb3af0a8817
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
