# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/property_tree
    REF 88a3b0ba8a6cd4ddf35f10d841bde9878241d64a
    SHA512 ad5ac8f0145e3cbce0aba3084629e1b3ba7e1de962a58dc892535f390724070f444671ed86bee6e4f20947456ebc2da8235614ee8fda5546319cb8283b3f0bc8
    HEAD_REF develop
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
