# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/container
    REF b8b089730ad7a9cd4a97f5796827177475462d0c
    SHA512 19970ae9aa537d9c6a513389ba8d86555a83ac41f4d1af937585eb941e39bc65be89df25fc2ed8250e8bd0c46adf029cc1de8b541f2d3ec69f200c60564dd0d8
    HEAD_REF develop
)

include(${CURRENT_HOST_INSTALLED_DIR}/share/boost-build/boost-modular-build.cmake)
boost_modular_build(SOURCE_PATH ${SOURCE_PATH})
include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
