# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/property_map_parallel
    REF boost-1.84.0.beta1
    SHA512 173fe8737592303710e00aaa707842b7078ab32fd51714d3ba3da3e605a3adcf993b8dd7e6cd2d0897035ffbf884ab9ab72e0a8fa191e7bd217ccfcc40ce8692
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
