# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/metaparse
    REF dd35492d40f8f15ff80d4690d63274de03a09250
    SHA512 34d42cf5fc990d2fa1d1afff60f89de429eebd286a6d67093af4d5dd6929e2f80bf6761c2ee3e67c6151e6abb172c8b4a9c90c93547f7f9b76c813ad71fd2fac
    HEAD_REF develop
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
