# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/metaparse
    REF boost-1.84.0.beta1
    SHA512 babe91b45219f9eb530a0d58870f378e8dba3a4bcb97f9c23fa876ce2dccc34a624991b2b3e8a8cadb4e63008b5badd710fab6d6fd1360cd2e7d0fbaf05ed086
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
