# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/multi_index
    REF 2b2c52a27f5800c6e5eb566cc330c4bbe2387de6
    SHA512 af4626487b4013ae0429cf21d0e1e743cd956c7a67e2a906b13683849fa8825e53b20eb2b7ba3486f8f4e08a2762c6cd02f110c8b7d9c0dddc26070ce30c6e71
    HEAD_REF develop
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
