# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/multi_index
    REF boost-1.84.0.beta1
    SHA512 6bd3ce5998bc5e21f9cc59d0e4398526b28e5b4501cb5c563cd2b0c715449a2550a4e627d2e50be339f9f7ea6b0bdb11fdc731397928f56e0d3aa2f8c6e7c987
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
