# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/graph
    REF f3158683b598c32ddcd99c143543d482d4c97e91
    SHA512 0af1a590de7e061a07610598a3ca939d544e0aee6d6b6d4e5f7d5831bfaaa2bd47df250a68141e2d7f13c11d89e86be622e7e47b9c89cdc4cceb2d1ac6e01e4a
    HEAD_REF develop
)

include(${CURRENT_HOST_INSTALLED_DIR}/share/boost-build/boost-modular-build.cmake)
boost_modular_build(SOURCE_PATH ${SOURCE_PATH})
include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
