# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/property_map
    REF 252f64913ec014d0e3b5362aecde36ce73298594
    SHA512 ad39f80e9488d12ebc5994eb23435c0576fd482b2dd0cd1539c21bf757972401fed4b6bf35b1b276a73d65d82a9f7ca6d0ba489cd542eb1c1acaf82375303c71
    HEAD_REF develop
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
