# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/property_map
    REF boost-1.84.0.beta1
    SHA512 5320c656c79499b1857255d705ebf84e6ed432ed91ed38646158e3da3e7449291eeaaf3266e320aef6453f46174008f8a8988cb7279eb1e3aa3d174c7656e382
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
