# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/interprocess
    REF boost-1.84.0.beta1
    SHA512 d5b3c125efff15099b1a2bebbbcb66c88e1525ab0da8d7e99b59f001086da49a62ae50b592e9a1503d52bfef6f0f2abe78749fa02fae00797222eae61adaa1ae
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
