# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/interprocess
    REF 718e17dd3e365d83c90f9a93ecad94a4dfcc07c5
    SHA512 072e844faa87fd1a4731add4136e5f91e63327e0a0045c299b7dcd9111d14f058738bc2382bce75490762c34be0f88ef8cc8af0a6da56008c7428de6190b15e2
    HEAD_REF develop
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
