# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/icl
    REF b2db8e5997f602caa2b6d4bc58d84a04f9de2d3f
    SHA512 699af02a195d75da0b66a4301a09c3559936dbe343a379c2b4defd71a77a2ebd2d20cf3b9b46697dc285cd02525ec76497987e1f3337fe9e35c80ca09c3c2109
    HEAD_REF develop
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
