# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/heap
    REF boost-1.84.0.beta1
    SHA512 7ae01511abda0f12a4169b444a032c46fbe5e408931c7a77d15abf935dad07d9b7954eb4ec3f8dd124bdae7040387363a9d2365cd0a52b25eaa1331c959dde83
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
