# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/chrono
    REF 8551ec1c5373621e5228a06cf0aacbb5c261560f
    SHA512 3a5c16c780399c2a515baca6bda46093324f7cbbefb4e67b0b46e7adbdba2a68a4fe7c0324d0865332c03bd65f795a541cdf50ba1d54e174d3e4ec282df9f79b
    HEAD_REF develop
)

include(${CURRENT_HOST_INSTALLED_DIR}/share/boost-build/boost-modular-build.cmake)
boost_modular_build(SOURCE_PATH ${SOURCE_PATH})
include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
