# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/unordered
    REF 73891c6ec8ee1b2896f7b8a3a29612d9a46daeac
    SHA512 dc49d24e202174e41307ace6f0f6acc860818cf00f59c6a30e8491229f7ddaa33656fce8b02785c439c60a9004a5b48dff5187f58382024b373ef03edb32e3b3
    HEAD_REF develop
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
