# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/unordered
    REF boost-1.84.0.beta1
    SHA512 e0d47bb5ffe8bda86ef6032cd3d29a544aea379a8b154b5b5972f44ffd0a72946490ce55d07f609be1efd2b6f9867c9db5b7f78e11b6ad03dba164600ca02594
    HEAD_REF master
    # PATCHES 0001-unordered-fix-copy-assign.patch
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
