# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/ptr_container
    REF boost-1.84.0.beta1
    SHA512 4ddc2276cc68ff9902c974721a203808de152d4fcd0113e225eaa6444b78fe638f1e96d1c7f64bf14710bf4dbc5ee8741654b2097575064e86ebca176fae2ba2
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
