# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/ptr_container
    REF b90a92d46a6c654a841a48f664d3ed64c4a2b8b0
    SHA512 d2a3a2a862e03c1e4d57881af3a13b8b0e1b88d666815e225ef7a277aa0953f5ba202b5b6ed69effd305423f72da0afa47662ab7fb8903922d152da43c4a1c22
    HEAD_REF develop
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
