# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/sort
    REF 9aa7e7d25f86c7acb3a6e2f29699fd4a564508fe
    SHA512 d39b4129f8bc907d8c8edfb277809365d857c4d416289976f8a2990c49d12291be8c02423632080a76f296318c067abbf082767dd8abd642ec7fce00f20de764
    HEAD_REF develop
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
